require 'cucumber/salad/widgets/widget'
require 'cucumber/salad/widgets/atom'
require 'cucumber/salad/widgets/action'
require 'cucumber/salad/widgets/list'
require 'cucumber/salad/widgets/base_table'
require 'cucumber/salad/widgets/auto_table'
require 'cucumber/salad/widgets/table'
require 'cucumber/salad/widgets/form'
