# This file describes the organization of the major Widget API components.

require 'dill/widgets/widget_class'
require 'dill/widgets/widget_checkpoint'
require 'dill/widgets/widget_container'
require 'dill/widgets/node_text'
require 'dill/widgets/widget_name'
require 'dill/widgets/widget'
require 'dill/widgets/list_item'
require 'dill/widgets/list'
require 'dill/widgets/base_table'
require 'dill/widgets/auto_table'
require 'dill/widgets/table'
require 'dill/widgets/field'
require 'dill/widgets/check_box'
require 'dill/widgets/select'
require 'dill/widgets/text_field'
require 'dill/widgets/field_group'
require 'dill/widgets/form'
require 'dill/widgets/document'
